import type { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: 'ab123cd',
    marca: 'Audi',
    modello: 'A3',
    versione: 'Sportback 35 TFSI S tronic',
    anno: 2022,
    chilometraggio: 45000,
    carburante: 'Benzina',
    cambio: 'Automatico',
    potenza: 150,
    colore_esterno: 'Grigio Daytona',
    prezzo: 32000,
    descrizione:
      "Scopri l'eleganza e le prestazioni dell'Audi A3 Sportback. Questo modello del 2022 combina un design sportivo con una tecnologia all'avanguardia, offrendo un'esperienza di guida dinamica e confortevole. Il motore 35 TFSI garantisce efficienza e reattività, mentre il cambio S tronic assicura passaggi di marcia fluidi e veloci. Perfetta per la città e per i lunghi viaggi, questa A3 è un'occasione da non perdere.",
    immagini: [
      'https://picsum.photos/seed/audi-a3-1/800/600',
      'https://picsum.photos/seed/audi-a3-2/800/600',
      'https://picsum.photos/seed/audi-a3-3/800/600',
      'https://picsum.photos/seed/audi-a3-4/800/600',
    ],
    link_canva: 'https://www.canva.com/design/DAF-1_2_3/view',
    stato: 'Pubblicato',
    consulente: 'Mario Rossi',
    telefono_consulente: '+393331234567',
  },
  {
    id: 'ef456gh',
    marca: 'BMW',
    modello: 'X1',
    versione: 'sDrive18d',
    anno: 2021,
    chilometraggio: 62000,
    carburante: 'Diesel',
    cambio: 'Automatico',
    potenza: 150,
    colore_esterno: 'Alpine White',
    prezzo: 34500,
    descrizione:
      "Versatilità e stile si fondono nel BMW X1 sDrive18d. Questo SUV compatto offre un'abitabilità eccezionale e un piacere di guida tipicamente BMW. Con il suo efficiente motore diesel e un allestimento ricco di optional, è l'auto ideale per chi cerca comfort, sicurezza e prestazioni. Le condizioni sono impeccabili, pronta per qualsiasi avventura.",
    immagini: [
      'https://picsum.photos/seed/bmw-x1-1/800/600',
      'https://picsum.photos/seed/bmw-x1-2/800/600',
      'https://picsum.photos/seed/bmw-x1-3/800/600',
    ],
    link_canva: 'https://www.canva.com/design/DAF-4_5_6/view',
    stato: 'Opzionato',
    consulente: 'Luca Bianchi',
    telefono_consulente: '+393337654321',
  },
  {
    id: 'ij789kl',
    marca: 'Mercedes-Benz',
    modello: 'Classe A',
    versione: 'A 200 d Automatic PREMIUM',
    anno: 2020,
    chilometraggio: 89000,
    carburante: 'Diesel',
    cambio: 'Automatico',
    potenza: 150,
    colore_esterno: 'Nero Cosmo',
    prezzo: 29800,
    descrizione:
      "La Mercedes-Benz Classe A ridefinisce il concetto di compatta di lusso. Con il suo design iconico e gli interni tecnologici dominati dal sistema MBUX, offre un'esperienza di guida senza pari. La versione Premium è dotata di tutti i comfort e le tecnologie più desiderate. Un'auto che non passa inosservata, ora disponibile ad un prezzo competitivo.",
    immagini: [
      'https://picsum.photos/seed/merc-a-1/800/600',
      'https://picsum.photos/seed/merc-a-2/800/600',
      'https://picsum.photos/seed/merc-a-3/800/600',
      'https://picsum.photos/seed/merc-a-4/800/600',
      'https://picsum.photos/seed/merc-a-5/800/600',
    ],
    link_canva: 'https://www.canva.com/design/DAF-7_8_9/view',
    stato: 'Venduto',
    consulente: 'Mario Rossi',
    telefono_consulente: '+393331234567',
  },
  {
    id: 'mn012op',
    marca: 'Fiat',
    modello: '500',
    versione: 'Hybrid Cult',
    anno: 2023,
    chilometraggio: 15000,
    carburante: 'Ibrida',
    cambio: 'Manuale',
    potenza: 70,
    colore_esterno: 'Rosso Passione',
    prezzo: 16500,
    descrizione:
      "L'icona italiana si rinnova con la tecnologia ibrida. La Fiat 500 Hybrid Cult è la city car perfetta: stile inconfondibile, consumi ridotti e un'agilità che la rende imbattibile nel traffico urbano. Questo esemplare del 2023 è praticamente nuovo, con pochissimi chilometri. Ideale per chi cerca un'auto alla moda, ecologica e divertente da guidare.",
    immagini: [
      'https://picsum.photos/seed/fiat-500-1/800/600',
      'https://picsum.photos/seed/fiat-500-2/800/600',
    ],
    link_canva: 'https://www.canva.com/design/DAF-10_11_12/view',
    stato: 'Pubblicato',
    consulente: 'Giulia Verdi',
    telefono_consulente: '+393331122334',
  },
  {
    id: 'qr345st',
    marca: 'Tesla',
    modello: 'Model 3',
    versione: 'Standard Range Plus',
    anno: 2022,
    chilometraggio: 33000,
    carburante: 'Elettrica',
    cambio: 'Automatico',
    potenza: 283,
    colore_esterno: 'Bianco Perla',
    prezzo: 38000,
    descrizione:
      "Entra nel futuro della mobilità con la Tesla Model 3. Prestazioni mozzafiato, autonomia eccellente e una tecnologia che ridefinisce l'esperienza di guida. Questo modello Standard Range Plus è perfetto per l'uso quotidiano e per i viaggi, grazie alla rete di Supercharger. Silenziosa, potente e a zero emissioni, è l'auto che hai sempre sognato.",
    immagini: [
      'https://picsum.photos/seed/tesla-3-1/800/600',
      'https://picsum.photos/seed/tesla-3-2/800/600',
      'https://picsum.photos/seed/tesla-3-3/800/600',
      'https://picsum.photos/seed/tesla-3-4/800/600',
    ],
    link_canva: 'https://www.canva.com/design/DAF-13_14_15/view',
    stato: 'Pubblicato',
    consulente: 'Luca Bianchi',
    telefono_consulente: '+393337654321',
  },
  {
    id: 'uv678wx',
    marca: 'Lancia',
    modello: 'Ypsilon',
    versione: '1.0 FireFly 70 CV Start&Stop Hybrid Argento',
    anno: 2021,
    chilometraggio: 55000,
    carburante: 'Ibrida',
    cambio: 'Manuale',
    potenza: 70,
    colore_esterno: 'Grigio Argento',
    prezzo: 14200,
    descrizione:
      "Lancia Ypsilon, la fashion city car per eccellenza. Questo modello ibrido unisce eleganza e rispetto per l'ambiente, garantendo consumi contenuti. L'allestimento Argento offre un look raffinato e una dotazione completa. Perfetta per chi desidera distinguersi in città con stile e intelligenza.",
    immagini: [
      'https://picsum.photos/seed/lancia-y-1/800/600',
      'https://picsum.photos/seed/lancia-y-2/800/600',
      'https://picsum.photos/seed/lancia-y-3/800/600',
    ],
    link_canva: 'https://www.canva.com/design/DAF-16_17_18/view',
    stato: 'Pubblicato',
    consulente: 'Giulia Verdi',
    telefono_consulente: '+393331122334',
  }
];
