import type { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: 'ab123cd',
    data_inserimento: '2024-07-26T10:00:00Z',
    marca: 'Audi',
    modello: 'A3',
    versione: 'Sportback 35 TFSI S tronic',
    anno: 2022,
    chilometraggio: 45000,
    carburante: 'Benzina',
    cambio: 'Automatico',
    potenza: 150,
    colore_esterno: 'Grigio Daytona',
    prezzo: 32000,
    descrizione:
      "Scopri l'eleganza e le prestazioni dell'Audi A3 Sportback. Questo modello del 2022 combina un design sportivo con una tecnologia all'avanguardia, offrendo un'esperienza di guida dinamica e confortevole. Il motore 35 TFSI garantisce efficienza e reattività, mentre il cambio S tronic assicura passaggi di marcia fluidi e veloci. Perfetta per la città e per i lunghi viaggi, questa A3 è un'occasione da non perdere.",
    immagini: [
      'https://images.unsplash.com/photo-1540066019607-e5f69323a8dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxhdWRpJTIwY2FyfGVufDB8fHx8MTc3MjU1MzEyN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    link_canva: 'https://www.canva.com/design/DAF-1_2_3/view',
    stato: 'In vendita',
  },
  {
    id: 'ef456gh',
    data_inserimento: '2024-07-26T10:00:00Z',
    marca: 'BMW',
    modello: 'X1',
    versione: 'sDrive18d',
    anno: 2021,
    chilometraggio: 62000,
    carburante: 'Diesel',
    cambio: 'Automatico',
    potenza: 150,
    colore_esterno: 'Alpine White',
    prezzo: 34500,
    descrizione:
      "Versatilità e stile si fondono nel BMW X1 sDrive18d. Questo SUV compatto offre un'abitabilità eccezionale e un piacere di guida tipicamente BMW. Con il suo efficiente motore diesel e un allestimento ricco di optional, è l'auto ideale per chi cerca comfort, sicurezza e prestazioni. Le condizioni sono impeccabili, pronta per qualsiasi avventura.",
    immagini: [
      'https://images.unsplash.com/photo-1635990215204-e7dd7bbae49d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxibXclMjBzdXZ8ZW58MHx8fHwxNzcyNTUzMTI3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    link_canva: 'https://www.canva.com/design/DAF-4_5_6/view',
    stato: 'In vendita',
  },
  {
    id: 'ij789kl',
    data_inserimento: '2024-07-26T10:00:00Z',
    marca: 'Mercedes-Benz',
    modello: 'Classe A',
    versione: 'A 200 d Automatic PREMIUM',
    anno: 2020,
    chilometraggio: 89000,
    carburante: 'Diesel',
    cambio: 'Automatico',
    potenza: 150,
    colore_esterno: 'Nero Cosmo',
    prezzo: 29800,
    descrizione:
      "La Mercedes-Benz Classe A ridefinisce il concetto di compatta di lusso. Con il suo design iconico e gli interni tecnologici dominati dal sistema MBUX, offre un'esperienza di guida senza pari. La versione Premium è dotata di tutti i comfort e le tecnologie più desiderate. Un'auto che non passa inosservata, ora disponibile ad un prezzo competitivo.",
    immagini: [
      'https://images.unsplash.com/photo-1630165646015-77e71874fa68?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8bWVyY2VkZXMlMjBjYXJ8ZW58MHx8fHwxNzcyNTUzMTI3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    link_canva: 'https://www.canva.com/design/DAF-7_8_9/view',
    stato: 'Venduto',
  },
  {
    id: 'mn012op',
    data_inserimento: '2024-07-26T10:00:00Z',
    marca: 'Fiat',
    modello: '500',
    versione: 'Hybrid Cult',
    anno: 2023,
    chilometraggio: 15000,
    carburante: 'Ibrida',
    cambio: 'Manuale',
    potenza: 70,
    colore_esterno: 'Rosso Passione',
    prezzo: 16500,
    descrizione:
      "L'icona italiana si rinnova con la tecnologia ibrida. La Fiat 500 Hybrid Cult è la city car perfetta: stile inconfondibile, consumi ridotti e un'agilità che la rende imbattibile nel traffico urbano. Questo esemplare del 2023 è praticamente nuovo, con pochissimi chilometri. Ideale per chi cerca un'auto alla moda, ecologica e divertente da guidare.",
    immagini: [
      'https://images.unsplash.com/photo-1662715087897-73bf72c850f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxmaWF0JTIwY2FyfGVufDB8fHx8MTc3MjU1MzEyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    link_canva: 'https://www.canva.com/design/DAF-10_11_12/view',
    stato: 'In vendita',
  },
  {
    id: 'qr345st',
    data_inserimento: '2024-07-26T10:00:00Z',
    marca: 'Tesla',
    modello: 'Model 3',
    versione: 'Standard Range Plus',
    anno: 2022,
    chilometraggio: 33000,
    carburante: 'Elettrica',
    cambio: 'Automatico',
    potenza: 283,
    colore_esterno: 'Bianco Perla',
    prezzo: 38000,
    descrizione:
      "Entra nel futuro della mobilità con la Tesla Model 3. Prestazioni mozzafiato, autonomia eccellente e una tecnologia che ridefinisce l'esperienza di guida. Questo modello Standard Range Plus è perfetto per l'uso quotidiano e per i viaggi, grazie alla rete di Supercharger. Silenziosa, potente e a zero emissioni, è l'auto che hai sempre sognato.",
    immagini: [
      'https://images.unsplash.com/photo-1744973270493-01a1f5e5e1c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHx0ZXNsYSUyMGVsZWN0cmljfGVufDB8fHx8MTc3MjU1MzEyN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    link_canva: 'https://www.canva.com/design/DAF-13_14_15/view',
    stato: 'In vendita',
  },
  {
    id: 'uv678wx',
    data_inserimento: '2024-07-26T10:00:00Z',
    marca: 'Lancia',
    modello: 'Ypsilon',
    versione: '1.0 FireFly 70 CV Start&Stop Hybrid Argento',
    anno: 2021,
    chilometraggio: 55000,
    carburante: 'Ibrida',
    cambio: 'Manuale',
    potenza: 70,
    colore_esterno: 'Grigio Argento',
    prezzo: 14200,
    descrizione:
      "Lancia Ypsilon, la fashion city car per eccellenza. Questo modello ibrido unisce eleganza e rispetto per l'ambiente, garantendo consumi contenuti. L'allestimento Argento offre un look raffinato e una dotazione completa. Perfetta per chi desidera distinguersi in città con stile e intelligenza.",
    immagini: [
      'https://images.unsplash.com/photo-1707492650689-200aa431d098?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxsYW5jaWElMjBjYXJ8ZW58MHx8fHwxNzcyNTUzMTI3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    link_canva: 'https://www.canva.com/design/DAF-16_17_18/view',
    stato: 'In vendita',
  },
  {
    id: 'yz012ab',
    data_inserimento: '2024-07-25T12:00:00Z',
    marca: 'Fiat',
    modello: 'Panda',
    versione: '1.0 70cv Hybrid City Cross',
    anno: 2022,
    chilometraggio: 22000,
    carburante: 'Ibrida',
    cambio: 'Manuale',
    potenza: 70,
    colore_esterno: 'Nero',
    prezzo: 15500,
    descrizione: "La Fiat Panda si conferma l'auto perfetta per la città. Agile, parsimoniosa grazie al motore ibrido e con lo stile inconfondibile dell'allestimento City Cross. Questo esemplare è in condizioni eccellenti e pronto a diventare il tuo compagno di avventure urbane.",
    immagini: [
      "https://www.nstre.it/files/web-auto/fiat/panda-iii-2021/N01021123/fiat-panda-1-0-70cv-firefly-hybrid-sands-gp481db-2.jpg"
    ],
    link_canva: "https://www.canva.com/design/DAF_sample/view",
    stato: 'In vendita'
  }
];
